// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/experience/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/experience">> = Specific
  const handler = {} as typeof import("../../app/experience/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ontology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ontology">> = Specific
  const handler = {} as typeof import("../../app/ontology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/compare">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/evidence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/evidence">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/evidence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/history">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/judgments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/judgments">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/judgments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/object-set/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/object-set">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/object-set/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/report">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/scope/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/scope">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/scope/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/stages/[stage]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/stages/[stage]">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/stages/[stage]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/structure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]/structure">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/structure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/new">> = Specific
  const handler = {} as typeof import("../../app/runs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs">> = Specific
  const handler = {} as typeof import("../../app/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ontology/[nodeId]/instances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ontology/[nodeId]/instances">> = Specific
  const handler = {} as typeof import("../../app/api/ontology/[nodeId]/instances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ontology/candidates/[candidateKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ontology/candidates/[candidateKey]">> = Specific
  const handler = {} as typeof import("../../app/api/ontology/candidates/[candidateKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ontology/candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ontology/candidates">> = Specific
  const handler = {} as typeof import("../../app/api/ontology/candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ontology/changes/[requestId]/actions/[actionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ontology/changes/[requestId]/actions/[actionId]">> = Specific
  const handler = {} as typeof import("../../app/api/ontology/changes/[requestId]/actions/[actionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ontology/changes/[requestId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ontology/changes/[requestId]">> = Specific
  const handler = {} as typeof import("../../app/api/ontology/changes/[requestId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ontology/changes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ontology/changes">> = Specific
  const handler = {} as typeof import("../../app/api/ontology/changes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ontology/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ontology">> = Specific
  const handler = {} as typeof import("../../app/api/ontology/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/radar/events/[id]/start-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/radar/events/[id]/start-update">> = Specific
  const handler = {} as typeof import("../../app/api/radar/events/[id]/start-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/radar/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/radar/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/radar/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/radar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/radar">> = Specific
  const handler = {} as typeof import("../../app/api/radar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/actions/[proposalId]/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/actions/[proposalId]/execute">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/actions/[proposalId]/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/actions/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/actions/proposals">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/actions/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/actions">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/archive.zip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/archive.zip">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/archive.zip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/archive/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/archive/file">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/archive/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/archive">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/artifacts/[artifactId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/artifacts/[artifactId]/approve">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/artifacts/[artifactId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/artifacts/[artifactId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/artifacts/[artifactId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/artifacts/[artifactId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/artifacts/[artifactId]/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/artifacts/[artifactId]/file">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/artifacts/[artifactId]/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/artifacts/[artifactId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/artifacts/[artifactId]">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/artifacts/[artifactId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/artifacts/[artifactId]/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/artifacts/[artifactId]/validate">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/artifacts/[artifactId]/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/baseline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/baseline">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/baseline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/change-set/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/change-set">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/change-set/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/continue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/continue">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/continue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/evaluation/recompute-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/evaluation/recompute-metrics">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/evaluation/recompute-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/evaluation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/evaluation">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/evaluation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/independent-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/independent-review">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/independent-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/jobs/[jobId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/jobs/[jobId]/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/jobs/[jobId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/jobs/[jobId]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/jobs/[jobId]/retry">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/jobs/[jobId]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/object-set/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/object-set">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/object-set/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/publish">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/relations/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/relations/options">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/relations/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/report.md/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/report.md">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/report.md/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/revise/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/revise">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/revise/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/sources/acquire/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/sources/acquire">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/sources/acquire/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/stages/01/clarify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/stages/01/clarify">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/stages/01/clarify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/stages/[stage]/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/stages/[stage]/generate">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/stages/[stage]/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/work-items/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/work-items/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/work-items/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/work-items/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/work-items/batch">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/work-items/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/[id]/work-items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/work-items">> = Specific
  const handler = {} as typeof import("../../app/api/runs/[id]/work-items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs">> = Specific
  const handler = {} as typeof import("../../app/api/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/runs/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/runs/[id]">> = Specific
  const handler = {} as typeof import("../../app/runs/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
