/**
 * Client-safe projection of formal ontology enum vocabularies.
 *
 * Authority remains 01_semantic/01_ontology/models/*.yaml. This file is generated by
 * scripts/generate-ontology-vocabulary.ts; do not edit it by hand.
 */
export const ONTOLOGY_ENUMS = {
  "AssetImpact.direction": ["positive", "negative", "mixed", "neutral", "indeterminate"],
  "AssetImpact.impact_channel": ["revenue", "margin", "cashflow", "valuation_multiple", "cost_of_capital", "liquidity", "mixed", "other"],
  "BlockingFactor.effect": ["method_block", "direction_block", "level_cap", "scope_cap"],
  "CapacityMetric.capacity_basis": ["nameplate", "effective", "qualified", "available"],
  "Chip.chip_category": ["logic", "memory", "analog", "power", "rf", "optoelectronic", "sensor", "discrete", "mixed_signal", "other"],
  "Event.event_type": ["commercial", "operational", "technology", "policy", "supply", "demand", "financial", "other"],
  "EvidenceAssessment.assessment": ["usable", "usable_with_caveat", "contested", "unusable"],
  "EvidenceAssessment.directness": ["direct", "indirect", "proxy"],
  "EvidenceBasket.role": ["support", "counter", "context", "boundary"],
  "EvidenceRequirement.evidence_role": ["support", "counter", "context", "boundary"],
  "ExpectationGap.direction": ["positive", "negative", "mixed", "none", "indeterminate"],
  "ExpectationGap.gap_kind": ["level_gap", "slope_gap", "timing_gap", "condition_gap", "mixed"],
  "FinancialInstrument.instrument_type": ["equity", "debt", "fund", "derivative", "depositary_receipt", "other"],
  "Judgment.confidence": ["low", "medium", "high"],
  "Judgment.conflict_status": ["none", "unresolved", "resolved", "decisive"],
  "Judgment.decision_status": ["draft", "supported", "contested", "blocked", "indeterminate", "invalidated"],
  "Judgment.level": ["J0", "J1", "J2", "J3", "J4"],
  "JudgmentUnit.judgment_type": ["state_measurement", "trend_direction", "cycle_phase", "mechanism_validation", "causal_attribution", "transmission_path", "object_differentiation", "impact_realization", "expectation_gap", "valuation_impact"],
  "ManufacturingFacility.facility_kind": ["wafer_fab", "packaging", "testing", "mask", "material", "equipment", "integrated"],
  "ManufacturingFacility.lifecycle_stage": ["planned", "under_construction", "pilot", "operating", "suspended", "retired"],
  "MarketExpectation.consensus_basis": ["sell_side_consensus", "buy_side_positioning", "market_implied", "mixed", "other"],
  "PolicyInstrument.instrument_type": ["restriction", "subsidy", "tax", "standard", "licensing", "disclosure", "other"],
  "ProductionLine.line_kind": ["front_end", "wafer_test", "packaging", "final_test", "material", "equipment"],
  "ResearchQuestion.failure_route": ["stop", "downgrade", "competing_explanation", "return_to_structure"],
  "ResearchScenario.scenario_type": ["CompanyResearch", "IndustryResearch", "ValueChainResearch", "TechnologyRouteResearch", "EventImpactResearch"],
  "ResearchScenario.status": ["entered", "in_progress", "complete", "invalidated"],
  "RuleEvaluation.result": ["pass", "fail", "contested", "blocked"],
  "SemiconductorEquipment.equipment_category": ["lithography", "etch", "deposition", "implant", "thermal", "clean", "cmp", "metrology", "inspection", "packaging", "test", "automation", "facility", "subsystem", "other"],
  "SemiconductorMaterial.material_category": ["wafer_substrate", "photoresist", "mask", "gas", "wet_chemical", "precursor", "target", "cmp", "packaging_substrate", "bonding", "encapsulation", "thermal", "consumable", "other"],
  "Signal.role": ["support", "weaken", "block", "context"],
  "SourceDocument.source_tier": ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"],
  "StateChange.direction": ["increase", "decrease", "unchanged", "transition", "indeterminate"],
  "TechnologyRoute.route_category": ["process_scaling", "device_architecture", "memory_architecture", "packaging", "interconnect", "compound_semiconductor", "photonics", "test", "system_integration", "other"],
  "YieldMetric.batch_scope": ["sample", "pilot", "mass_production", "blended"],
} as const;

export const ONTOLOGY_JUDGMENT_TYPES = ONTOLOGY_ENUMS["JudgmentUnit.judgment_type"];

export const ONTOLOGY_JUDGMENT_LEVELS = ONTOLOGY_ENUMS["Judgment.level"];

export const ONTOLOGY_CONFIDENCE_LEVELS = ONTOLOGY_ENUMS["Judgment.confidence"];

export const ONTOLOGY_SOURCE_TIERS = ONTOLOGY_ENUMS["SourceDocument.source_tier"];

export type OntologyJudgmentType = (typeof ONTOLOGY_JUDGMENT_TYPES)[number];
export type OntologyJudgmentLevel = (typeof ONTOLOGY_JUDGMENT_LEVELS)[number];
export type OntologyConfidenceLevel = (typeof ONTOLOGY_CONFIDENCE_LEVELS)[number];
export type OntologySourceTier = (typeof ONTOLOGY_SOURCE_TIERS)[number];
