// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/experience" | "/ontology" | "/runs" | "/runs/[id]" | "/runs/[id]/compare" | "/runs/[id]/evidence" | "/runs/[id]/history" | "/runs/[id]/judgments" | "/runs/[id]/object-set" | "/runs/[id]/report" | "/runs/[id]/scope" | "/runs/[id]/stages/[stage]" | "/runs/[id]/structure" | "/runs/new"
type AppRouteHandlerRoutes = "/api/ontology" | "/api/ontology/[nodeId]/instances" | "/api/ontology/candidates" | "/api/ontology/candidates/[candidateKey]" | "/api/ontology/changes" | "/api/ontology/changes/[requestId]" | "/api/ontology/changes/[requestId]/actions/[actionId]" | "/api/radar" | "/api/radar/events/[id]/start-update" | "/api/radar/refresh" | "/api/runs" | "/api/runs/[id]" | "/api/runs/[id]/actions" | "/api/runs/[id]/actions/[proposalId]/execute" | "/api/runs/[id]/actions/proposals" | "/api/runs/[id]/archive" | "/api/runs/[id]/archive.zip" | "/api/runs/[id]/archive/file" | "/api/runs/[id]/artifacts/[artifactId]" | "/api/runs/[id]/artifacts/[artifactId]/approve" | "/api/runs/[id]/artifacts/[artifactId]/cancel" | "/api/runs/[id]/artifacts/[artifactId]/file" | "/api/runs/[id]/artifacts/[artifactId]/validate" | "/api/runs/[id]/baseline" | "/api/runs/[id]/change-set" | "/api/runs/[id]/continue" | "/api/runs/[id]/evaluation" | "/api/runs/[id]/evaluation/recompute-metrics" | "/api/runs/[id]/independent-review" | "/api/runs/[id]/jobs/[jobId]/cancel" | "/api/runs/[id]/jobs/[jobId]/retry" | "/api/runs/[id]/object-set" | "/api/runs/[id]/publish" | "/api/runs/[id]/relations/options" | "/api/runs/[id]/report.md" | "/api/runs/[id]/revise" | "/api/runs/[id]/sources/acquire" | "/api/runs/[id]/stages/01/clarify" | "/api/runs/[id]/stages/[stage]/generate" | "/api/runs/[id]/status" | "/api/runs/[id]/work-items" | "/api/runs/[id]/work-items/[itemId]" | "/api/runs/[id]/work-items/batch"
type PageRoutes = never
type LayoutRoutes = "/" | "/runs/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ontology": {}
  "/api/ontology/[nodeId]/instances": { "nodeId": string; }
  "/api/ontology/candidates": {}
  "/api/ontology/candidates/[candidateKey]": { "candidateKey": string; }
  "/api/ontology/changes": {}
  "/api/ontology/changes/[requestId]": { "requestId": string; }
  "/api/ontology/changes/[requestId]/actions/[actionId]": { "requestId": string; "actionId": string; }
  "/api/radar": {}
  "/api/radar/events/[id]/start-update": { "id": string; }
  "/api/radar/refresh": {}
  "/api/runs": {}
  "/api/runs/[id]": { "id": string; }
  "/api/runs/[id]/actions": { "id": string; }
  "/api/runs/[id]/actions/[proposalId]/execute": { "id": string; "proposalId": string; }
  "/api/runs/[id]/actions/proposals": { "id": string; }
  "/api/runs/[id]/archive": { "id": string; }
  "/api/runs/[id]/archive.zip": { "id": string; }
  "/api/runs/[id]/archive/file": { "id": string; }
  "/api/runs/[id]/artifacts/[artifactId]": { "id": string; "artifactId": string; }
  "/api/runs/[id]/artifacts/[artifactId]/approve": { "id": string; "artifactId": string; }
  "/api/runs/[id]/artifacts/[artifactId]/cancel": { "id": string; "artifactId": string; }
  "/api/runs/[id]/artifacts/[artifactId]/file": { "id": string; "artifactId": string; }
  "/api/runs/[id]/artifacts/[artifactId]/validate": { "id": string; "artifactId": string; }
  "/api/runs/[id]/baseline": { "id": string; }
  "/api/runs/[id]/change-set": { "id": string; }
  "/api/runs/[id]/continue": { "id": string; }
  "/api/runs/[id]/evaluation": { "id": string; }
  "/api/runs/[id]/evaluation/recompute-metrics": { "id": string; }
  "/api/runs/[id]/independent-review": { "id": string; }
  "/api/runs/[id]/jobs/[jobId]/cancel": { "id": string; "jobId": string; }
  "/api/runs/[id]/jobs/[jobId]/retry": { "id": string; "jobId": string; }
  "/api/runs/[id]/object-set": { "id": string; }
  "/api/runs/[id]/publish": { "id": string; }
  "/api/runs/[id]/relations/options": { "id": string; }
  "/api/runs/[id]/report.md": { "id": string; }
  "/api/runs/[id]/revise": { "id": string; }
  "/api/runs/[id]/sources/acquire": { "id": string; }
  "/api/runs/[id]/stages/[stage]/generate": { "id": string; "stage": string; }
  "/api/runs/[id]/stages/01/clarify": { "id": string; }
  "/api/runs/[id]/status": { "id": string; }
  "/api/runs/[id]/work-items": { "id": string; }
  "/api/runs/[id]/work-items/[itemId]": { "id": string; "itemId": string; }
  "/api/runs/[id]/work-items/batch": { "id": string; }
  "/experience": {}
  "/ontology": {}
  "/runs": {}
  "/runs/[id]": { "id": string; }
  "/runs/[id]/compare": { "id": string; }
  "/runs/[id]/evidence": { "id": string; }
  "/runs/[id]/history": { "id": string; }
  "/runs/[id]/judgments": { "id": string; }
  "/runs/[id]/object-set": { "id": string; }
  "/runs/[id]/report": { "id": string; }
  "/runs/[id]/scope": { "id": string; }
  "/runs/[id]/stages/[stage]": { "id": string; "stage": string; }
  "/runs/[id]/structure": { "id": string; }
  "/runs/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/runs/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
