import { KnowledgeRunSelector } from "@/app/components/knowledge-run-selector";
import { loadTaskKnowledgePage } from "@/app/lib/knowledge-page-data";
import { stageLabel } from "@/app/lib/ui-labels";

export const dynamic = "force-dynamic";

function capabilityLabel(value: string) { return ({ judgment_structure: "判断结构", evidence: "取证方法", adjudication: "裁决方法" } as Record<string, string>)[value] || "研究方法"; }
function statusLabel(value: string) { return ({ approved: "已确认应用", needs_review: "待确认使用", selected: "已选择", executed: "已执行", candidate: "候选" } as Record<string, string>)[value] || value; }

export default async function TaskKnowledgeApplicationsPage({ searchParams }: { searchParams: Promise<{ runId?: string }> }) {
  const query = await searchParams;
  const { runs, selectedRun, dashboard } = loadTaskKnowledgePage(query.runId);
  return <section className="knowledge-task-page">
    <KnowledgeRunSelector runs={runs} selectedRun={selectedRun} action="/knowledge/task/applications"><span className="knowledge-question-help">本页回答：研究实际采用了什么？哪些是任务专用候选？可以导出什么？</span></KnowledgeRunSelector>
    {dashboard && selectedRun ? <>
      <section className="knowledge-outcome-strip"><article><span>实际采用阶段</span><strong>{dashboard.stageApplications.length}</strong><small>来自研究产物记录</small></article><article><span>研究方法</span><strong>{dashboard.methods.length}</strong><small>已确认与待确认分列</small></article><article className={dashboard.localCandidates.length ? "attention" : ""}><span>需关注候选</span><strong>{dashboard.localCandidates.length}</strong><small>{dashboard.localCandidates.length ? "治理前仅本任务有效" : "没有任务专用概念"}</small></article></section>
      <section className="knowledge-section-block"><div className="knowledge-block-heading"><div><span className="knowledge-step-kicker">1 · 先核对真实记录</span><h2>这项研究实际采用的知识</h2><p>只把研究产物中登记的知识版本、方法和输入上下文算作实际使用；按需生成的任务切片会明确标记为可导出。</p></div></div><div className="knowledge-application-grid">
        <article className="card knowledge-application-panel"><div className="panel-title"><h3>各阶段采用记录</h3><span>{dashboard.stageApplications.length} 个阶段</span></div><div className="knowledge-rows">{dashboard.stageApplications.map((item) => <div key={item.artifact_id}><span>{stageLabel(item.stage)}</span><strong>{statusLabel(item.status)}</strong><small>产物 v{item.artifact_version} · {item.knowledge_version?.slice(0, 20) || "未登记知识版本"}</small></div>)}</div></article>
        <article className="card knowledge-application-panel"><div className="panel-title"><h3>实际采用的研究方法</h3><span>{dashboard.methods.length} 项</span></div><div className="knowledge-rows">{dashboard.methods.map((method) => <div key={`${method.stage}:${method.method_id}`}><span>{capabilityLabel(method.capability_type)}</span><strong>{method.name}</strong><small>{stageLabel(method.stage)} · {statusLabel(method.status)} · v{method.method_version}</small></div>)}{!dashboard.methods.length ? <p className="muted">当前产物尚未登记方法应用。</p> : null}</div></article>
        <article className="card knowledge-application-panel candidate-panel"><div className="panel-title"><h3>任务专用、尚未正式化</h3><span>{dashboard.localCandidates.length} 项</span></div><div className="knowledge-rows">{dashboard.localCandidates.map((candidate) => <div key={candidate.ontology_node_id}><span>仅本任务生效</span><strong>{candidate.name}</strong><small>{candidate.definition || "尚无稳定定义"} · 使用位置 {candidate.judgment_unit_ids.join("、") || "未登记"}</small></div>)}{!dashboard.localCandidates.length ? <p className="muted">当前研究没有新增任务专用概念。</p> : null}</div></article>
      </div></section>
      <section className="knowledge-section-block"><div className="knowledge-block-heading"><div><span className="knowledge-step-kicker">2 · 再决定是否复用</span><h2>知识包与注入文件</h2><p>任务知识包是当前上下文的可导出切片，不会冒充历史 knowledge lock；正式基线不会包含 task_local。</p></div></div><div className="knowledge-detail-grid"><article className="card knowledge-package-card"><div><span className="knowledge-step-kicker">可导出任务切片</span><h3>{dashboard.taskPackage.package_id}</h3><p>由当前研究上下文生成，便于复用和审查。</p></div><dl><div><dt>正式定义</dt><dd>{String(dashboard.taskPackage.manifest.contents.ontology_definitions || 0)}</dd></div><div><dt>非正式本体</dt><dd>{String(dashboard.taskPackage.manifest.contents.task_local_ontology || 0)}</dd></div><div><dt>方法</dt><dd>{String(dashboard.taskPackage.manifest.contents.methods || 0)}</dd></div><div><dt>映射</dt><dd>{String(dashboard.taskPackage.manifest.contents.mapping_profiles || 0)}</dd></div></dl><a className="button" href={`/api/knowledge/package?kind=knowledge_task_slice&runId=${selectedRun.id}`}>下载任务知识包 ↓</a></article><article className="card knowledge-files-card"><div className="panel-title"><h3>逐阶段注入文件</h3><span>{dashboard.knowledgeFiles.length} 个文件</span></div><details><summary>查看技术文件与映射</summary><ul>{dashboard.knowledgeFiles.map((file) => <li key={file}><code>{file}</code></li>)}</ul>{dashboard.mappingProfileIds.length ? <p>映射：{dashboard.mappingProfileIds.join("、")}</p> : <p className="muted">当前产物未登记数据映射。</p>}</details></article></div>
        <article className="card knowledge-impact-panel"><div className="panel-title"><h3>证据怎样影响判断</h3><span>{dashboard.evidenceImpacts.length} 条已确认事实</span></div><div className="knowledge-impact-list">{dashboard.evidenceImpacts.map((result) => <details key={result.evidence.id}><summary><strong>{result.evidence.label}</strong><span>{result.impacted_judgments.length} 个下游判断</span></summary>{result.impacted_judgments.map((judgment) => <div key={judgment.id}><strong>{judgment.label}</strong><p>{judgment.path_labels.join(" → ") || "尚未形成显式影响路径"}</p></div>)}</details>)}{!dashboard.evidenceImpacts.length ? <p className="muted">当前研究还没有可追溯的已确认事实。</p> : null}</div></article>
      </section>
    </> : <div className="knowledge-selection-empty"><strong>选择研究后，这里会展示真实采用记录和知识包。</strong></div>}
  </section>;
}
