import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import YAML from "yaml";

const repositoryRoot = path.resolve(import.meta.dirname, "../..");
const targetFile = path.join(repositoryRoot, "07_runtime/skills/ontology/vocabulary.ts");
const modelRegistry = YAML.parse(
  readFileSync(path.join(repositoryRoot, "01_semantic/01_ontology/model_registry.yaml"), "utf8"),
) as Record<string, unknown>;
if (modelRegistry.schema_name !== "ontology_model_registry" || !Array.isArray(modelRegistry.model_files)) {
  throw new Error("正式本体模型注册表非法");
}
const modelFiles = modelRegistry.model_files.map((file) => String(file).replace(/^models\//, ""));

function model(file: string) {
  return YAML.parse(
    readFileSync(path.join(repositoryRoot, "01_semantic/01_ontology/models", file), "utf8"),
  ) as Record<string, any>;
}

function enumCatalog() {
  const catalog = new Map<string, string[]>();
  for (const file of modelFiles) {
    const document = model(file);
    for (const [objectType, definition] of Object.entries<any>(document.object_types || {})) {
      for (const [attribute, field] of Object.entries<any>(definition.attributes || definition.properties || {})) {
        if (field?.type !== "enum" || !Array.isArray(field.allowed_values) || !field.allowed_values.length) continue;
        const key = `${objectType}.${attribute}`;
        if (catalog.has(key)) throw new Error(`正式本体枚举键重复: ${key}`);
        catalog.set(key, field.allowed_values.map(String));
      }
    }
  }
  return [...catalog.entries()].sort(([left], [right]) => left.localeCompare(right));
}

function renderCatalog(entries: Array<[string, string[]]>) {
  return `{\n${entries
    .map(([key, items]) => `  ${JSON.stringify(key)}: [${items.map((item) => JSON.stringify(item)).join(", ")}],`)
    .join("\n")}\n} as const`;
}

const output = `/**
 * Client-safe projection of formal ontology enum vocabularies.
 *
 * Authority remains 01_semantic/01_ontology/models/*.yaml. This file is generated by
 * scripts/generate-ontology-vocabulary.ts; do not edit it by hand.
 */
export const ONTOLOGY_ENUMS = ${renderCatalog(enumCatalog())};

export const ONTOLOGY_JUDGMENT_TYPES = ONTOLOGY_ENUMS["JudgmentUnit.judgment_type"];

export const ONTOLOGY_JUDGMENT_LEVELS = ONTOLOGY_ENUMS["Judgment.level"];

export const ONTOLOGY_CONFIDENCE_LEVELS = ONTOLOGY_ENUMS["Judgment.confidence"];

export const ONTOLOGY_SOURCE_TIERS = ONTOLOGY_ENUMS["SourceDocument.source_tier"];

export type OntologyJudgmentType = (typeof ONTOLOGY_JUDGMENT_TYPES)[number];
export type OntologyJudgmentLevel = (typeof ONTOLOGY_JUDGMENT_LEVELS)[number];
export type OntologyConfidenceLevel = (typeof ONTOLOGY_CONFIDENCE_LEVELS)[number];
export type OntologySourceTier = (typeof ONTOLOGY_SOURCE_TIERS)[number];
`;

if (process.argv.includes("--check")) {
  const current = readFileSync(targetFile, "utf8");
  if (current !== output) {
    throw new Error("本体枚举投影已漂移；请运行 npm run ontology:sync");
  }
} else {
  writeFileSync(targetFile, output, "utf8");
}
