#!/usr/bin/env python3
"""Generate the browser/server-safe Ontology 4.0 catalog projection."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import yaml


RUNTIME = Path(__file__).resolve().parents[1]
ROOT = RUNTIME.parent
ONTOLOGY = ROOT / "01_semantic/01_ontology"
OUTPUT = RUNTIME / "src/ontology/generated.ts"


def load(path: Path) -> dict[str, Any]:
    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: root must be a mapping")
    return value


def main() -> int:
    registry = load(ONTOLOGY / "platform_registry.yaml")
    files = [ONTOLOGY / "platform_registry.yaml", ONTOLOGY / str(registry["meta_schema"])]
    files += [ONTOLOGY / str(item) for item in registry.get("semantic_models") or []]
    files += [ONTOLOGY / str(item) for item in registry.get("operational_models") or []]
    files += [ONTOLOGY / str(item) for item in (registry.get("kinetic_models") or {}).values()]

    objects: dict[str, Any] = {}
    relations: dict[str, Any] = {}
    for path in files:
        doc = load(path)
        for object_id, value in (doc.get("object_types") or {}).items():
            metadata = value.get("metadata") or {}
            objects[object_id] = {
                "id": object_id,
                "labelZh": metadata.get("label_zh") or value.get("label_zh") or object_id,
                "description": metadata.get("definition") or value.get("description") or "",
                "attributes": value.get("attributes") or {},
                "schemaVersion": doc.get("schema_version"),
                "namespace": metadata.get("namespace") or doc.get("namespace"),
            }
        for relation_id, value in (doc.get("relation_types") or {}).items():
            relations[relation_id] = {
                "id": relation_id,
                "sourceTypes": value.get("source_types") or [],
                "targetTypes": value.get("target_types") or [],
                "inverseOf": value.get("inverse_of"),
                "schemaVersion": doc.get("schema_version"),
            }

    kinetics = registry["kinetic_models"]
    actions = load(ONTOLOGY / kinetics["actions"]).get("actions") or {}
    functions = load(ONTOLOGY / kinetics["functions"]).get("functions") or {}
    policies = load(ONTOLOGY / kinetics["policies"]).get("policies") or {}
    triggers = load(ONTOLOGY / kinetics["triggers"]).get("triggers") or {}
    digest = hashlib.sha256()
    for path in files:
        digest.update(str(path.relative_to(ROOT)).encode())
        digest.update(path.read_bytes())
    payload = {
        "platformVersion": registry["schema_version"],
        "fingerprint": f"sha256:{digest.hexdigest()}",
        "objects": objects,
        "relations": relations,
        "actions": actions,
        "functions": functions,
        "policies": policies,
        "triggers": triggers,
    }
    serialized = json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=2)
    content = "// Generated by scripts/generate-ontology-catalog.py. Do not edit manually.\n" + f"export const ONTOLOGY_CATALOG = {serialized} as const;\n"
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print("Ontology generated catalog is stale; run npm run ontology:sync")
            return 1
    else:
        OUTPUT.write_text(content, encoding="utf-8")
    print(f"{'checked' if '--check' in sys.argv else 'generated'} {OUTPUT.relative_to(ROOT)} ({len(objects)} objects, {len(relations)} relations, {len(actions)} actions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
